version: '3'
services:
  solr:
    build:
      context: ./solr
      dockerfile: Dockerfile
    ports:
      - "8983:8983"
    container_name: solr
    environment:
      - SOLR_OPTS=-XX:-UseLargePages
      - JAVA_OPTS='-Xmx1g'
    deploy:
      resources:
        limits:
          memory: 1536M
        reservations:
          memory: 1024M
  indexer:
    build:
      context: ./indexer
      dockerfile: Dockerfile
    container_name: indexer
    environment:
      SOLR_COLLECTION_URL: "http://solr:8983/solr/intellij_core"
    depends_on:
      - solr
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10
  search-ui:
    container_name: search-ui
    build:
      context: ./search-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - NODE_ENV=development
    command: yarn start
volumes:
  data:
